package edu.jm.tabulavia.ui

import androidx.compose.ui.graphics.Color

object EmojiMapper {

    private val animalEmojis = listOf(
        "🐵",
        "🐒",
        "🦍",
        "🦧",
        "🐶",
        "🐕",
        "🦮",
        "🐕‍🦺",
        "🐩",
        "🐺",
        "🦊",
        "🦝",
        "🐱",
        "🐈",
        "🐈‍⬛",
        "🦁",
        "🐯",
        "🐅",
        "🐆",
        "🐴",
        "🐎",
//        "🦄",
        "🦓",
        "🦌",
        "🦬",
//        "🐮",
        "🐂",
        "🐃",
        "🐄",
//        "🐷",
//        "🐖",
        "🐗",
//       "🐽",
        "🐏",
        "🐑",
        "🐐",
//       "🐪",
        "🐫",
        "🦙",
        "🦒",
        "🐘",
        "🦣",
        "🦏",
        "🦛",
        "🐭",
        "🐁",
//       "🐀",
        "🐹",
        "🐰",
        "🐇",
        "🐿️",
        "🦫",
        "🦔",
        "🦇",
        "🐻",
        "🐻‍❄️",
        "🐨",
        "🐼",
//       "🦥",
        "🦦",
//       "🦨",
        "🦘",
        "🦡",
//       "🐾",
        "🦃",
//       "🐔",
        "🐓",
//       "🐣",
//       "🐤",
//       "🐥",
        "🐦",
        "🐧",
        "🕊️",
        "🦅",
        "🦆",
        "🦢",
        "🦉",
        "🦤",
        "🦩",
//       "🦚",
        "🦜",
//       "🐸",
        "🐊",
        "🐢",
        "🦎",
        "🐍",
        "🐲",
        "🐉",
        "🦕",
        "🦖",
//       "🐳",
        "🐋",
        "🐬",
        "🦭",
        "🐟",
        "🐠",
        "🐡",
        "🦈",
        "🐙",
//       "🐚",
//       "🐌",
        "🦋",
//       "🐛",
        "🐜",
        "🐝",
//       "🪲",
        "🐞",
        "🦗",
//       "🪳",
        "🕷️",
//       "🕸️",
//       "🦂",
//       "🦟",
//       "🪰",
//       "🪱",
//       "🦠"
    )

    fun mapStudentIdToEmoji(studentId: Long): String {
        val index = (studentId.mod(animalEmojis.size.toLong())).toInt()
        return animalEmojis[index]
    }

    /**
     * Generate a deterministic color from a Long ID using HSV.
     * This ensures the same ID always gets the same color, and the colors are visually pleasant (pastel).
     */
    fun generateColorFromId(id: Long): Color {
        val hue = (id * 137 % 360).toFloat()
        val saturation = 0.5f
        val value = 0.9f

        return Color.hsv(hue, saturation, value)
    }
}