/**
 * Activity entity for the 'activities' table.
 * Represents a learning activity associated with a course.
 */

package edu.jm.tabulavia.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
@Entity(
    tableName = "activities",
    foreignKeys = [
        ForeignKey(
            entity = Course::class,
            parentColumns = ["classId"],
            childColumns = ["classId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["classId"]),
        Index(value = ["firestoreId"], unique = true)
    ]
)
data class Activity(

    /**
     * Local identifier generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val activityId: Long = 0,

    /**
     * Firestore document identifier.
     */
    val firestoreId: String? = null,

    /**
     * Identifier of the associated course.
     */
    val classId: Long,

    /**
     * Title of the activity.
     */
    val title: String,

    /**
     * Detailed description of the activity.
     */
    val description: String,

    /**
     * Optional due date timestamp.
     */
    val dueDate: Long? = null
)