/**
 * ClassSession entity for the 'class_sessions' table.
 * Represents a class meeting stored locally and synchronized with Firestore.
 */
package edu.jm.tabulavia.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
@Entity(
    tableName = "class_sessions",
    foreignKeys = [
        ForeignKey(
            entity = Course::class,
            parentColumns = ["classId"],
            childColumns = ["classId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["classId"]),
        Index(value = ["firestoreId"], unique = true)
    ]
)
data class ClassSession(

    /**
     * Local identifier generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val sessionId: Long = 0,

    /**
     * Firestore document identifier.
     */
    val firestoreId: String? = null,

    /**
     * Identifier of the associated course.
     */
    val classId: Long,

    /**
     * Timestamp representing when the session occurred.
     */
    val timestamp: Long = System.currentTimeMillis()
)