/**
 * Course entity for the 'classes' table.
 * Represents a course stored locally and synchronized with Firestore.
 */
package edu.jm.tabulavia.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
@Entity(tableName = "classes")
data class Course(

    /**
     * Local identifier generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val classId: Long = 0,

    /**
     * Firestore document identifier.
     */
    val firestoreId: String? = null,

    /**
     * Name of the class.
     */
    val className: String,

    /**
     * Academic year associated with the class.
     */
    val academicYear: String,

    /**
     * Period or term of the class.
     */
    val period: String,

    /**
     * Number of class sessions planned.
     */
    val numberOfClasses: Int = 0
)