/**
 * GroupMember entity for the 'group_members' table.
 * Represents the membership of a student in a group for a specific activity.
 */

package edu.jm.tabulavia.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
@Entity(
    tableName = "group_members",
    foreignKeys = [
        ForeignKey(
            entity = Activity::class,
            parentColumns = ["activityId"],
            childColumns = ["activityId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Student::class,
            parentColumns = ["studentId"],
            childColumns = ["studentId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["activityId"]),
        Index(value = ["studentId"]),
        Index(value = ["firestoreId"], unique = true)
    ]
)
data class GroupMember(

    /**
     * Local identifier generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val groupMemberId: Long = 0,

    /**
     * Firestore document identifier.
     */
    val firestoreId: String? = null,

    /**
     * Identifier of the associated activity.
     */
    val activityId: Long,

    /**
     * Identifier of the associated student.
     */
    val studentId: String?,

    /**
     * Group number within the activity.
     */
    val groupNumber: Int
)