/**
 * SkillAssessment entity for the 'skill_assessments' table.
 * Represents an evaluation of a student's skill from a specific source.
 */

package edu.jm.tabulavia.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
@Entity(
    tableName = "skill_assessments",
    indices = [
        Index(value = ["studentId"]),
        Index(value = ["skillName"]),
        Index(value = ["firestoreId"], unique = true)
    ]
)
data class SkillAssessment(

    /**
     * Local identifier generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Firestore document identifier.
     */
    val firestoreId: String? = null,

    /**
     * Identifier of the assessed student.
     */
    val studentId: String,

    /**
     * Name of the assessed skill.
     */
    val skillName: String,

    /**
     * Level attributed in the assessment.
     */
    val level: SkillLevel,

    /**
     * Source of the assessment.
     */
    val source: AssessmentSource,

    /**
     * Timestamp when the assessment was recorded.
     */
    val timestamp: Long = System.currentTimeMillis(),

    /**
     * Identifier of the assessor when applicable.
     */
    val assessorId: Long? = null
)